### ISSUE TITLE
add files

### ISSUE THREAD

**Issue by rhaynes74** [ardunn/dex#48]
Hi folks, is it possible to quickly add files (.pdf, .tex, .c etc) to a project? Can notes be associated with projects? with files?

**Comment by ardunn** [comment]
Hey there @rhaynes74 I had not considered adding non-task files to a project. dex is mostly used for keeping track of tasks (.md files), and is secondarily a place to keep notes and other files related to tasks/projects. I had originally considered adding a "notes" interface but I think this is somewhat outside the scope of what dex would be useful for.

Within a project folder, you can keep whatever files you want in whatever structure you want as long as they're not ".md" files. 

So you might structure a project like this:

```
some_project
├── some_notes
│   ├── file.pdf
│   └── file.tex
├── srcfile1.c
├── srcfile2.c
└── tasks
    └── some_dex_task.md
```

The only folder dex actually needs is the tasks subdir within a project. But dex does not have any interface for adding non-md files to your project.

**Comment by rhaynes74** [comment]
Hi Alex - thanks for the reply.  Any suggestions of a cli tool that is capable of what I would like?

Sincerely,

Dr. Ronald D. Haynes

Professor, Department of Mathematics and Statistics
Chair, MSc and PhD Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by ardunn** [comment]
hey ronald, I don't have any recommendations, but that actually brings up an interesting problem. Maybe it will be something I incorporate into dex in the future
